---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
editor_options:
  chunk_output_type: console
---

## Clear workspace and load JAMP

```{r include=FALSE}
# Clear workspace and close all graphics devices --------------------------

rm(list = ls())
graphics.off()

library(JAMP)

```


## Set working directory to proper folder

```{r include=FALSE}

# set working directory to proper repo

setwd("/Users/jaredfreedman/Research/git/edna_metabarcoding/GC_VR_MiSeq_2021")

```

## Check for PhiX

```{r include=FALSE}
# check for PhiX

# only subsample 10000 reads

if(T){
  system2("vsearch", 
          "-fastx_subsample GC_VR_MiSeq_Demulti/Undetermined_S0_R1_001.fastq -fastaout GC_VR_MiSeq_Demulti/Undetermined_S0_R1_001.fastq -sample_pct 100")
} else { # check all reads in read 1 for PhiX
  system2("paste",
          " - - - - < /GC_VR_MiSeq_Demulti/Undetermined_S0_R1_001.fastq | cut -f 1,2 | sed 's/^@/>/' | tr \"\t\" \"\n\" > /GC_VR_MiSeq_Demulti/Undetermined_S0_R1_001.fastq")
}


system2("vsearch",
        "-usearch_global /GC_VR_MiSeq_Demulti/Undetermined_S0_R1_001.fastq -db /Users/jaredfreedman/Research/git/JAMP/Tutorial/PhiX.fasta -id 0.9 -strand both -blast6out PhiX_table.txt -maxrejects 1 -maxaccepts 1")
```

## Merge pair end reads

```{r}


files <- list.files("GC_VR_MiSeq_Demulti", full.names=T)
files

Merge_PE(files = "latest")

```

